name: Build

on:
  push:
    branches: [experiment/**]
  pull_request:
    branches: [main]
  workflow_run:
    workflows: ["Update Emacs Source"]
    branches: [main]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#example-workflow-configuration
  workflow_dispatch:

jobs:
  build-all:
    runs-on: macos-latest
    steps:
      # setup nix and cachix environment
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
      - uses: cachix/cachix-action@v10
        with:
          name: emacs-osx
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Attempt nix-build
        run: nix-build

      - name: Build success, tag as "latest"
        if: ${{ success() }}
        run: |
          git fetch --all --tags
          git pull --rebase --autostash
          git tag -d built
          git push origin :refs/tags/built
          git tag built
          git push origin built
